"""Add published_at column to Position

Revision ID: 5e28ed1437f9
Revises: b35c511c9f90
Create Date: 2025-02-25 15:03:53.557112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e28ed1437f9'
down_revision = 'b35c511c9f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'position', ['position_id'], ['id'])

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_column('published_at')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('position_id')
        batch_op.drop_column('content')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
